language: android
jdk: oraclejdk8
notifications:
  email:
    - external-ci-notifications+braintree-android-drop-in@getbraintree.com
sudo: true
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-26
    - extra-google-m2repository
script: ./gradlew --stacktrace lint test :Demo:assembleDebug :Demo:assembleRelease
after_success: ./script/deploy_snapshot.sh
